name: Update Metadata Hash

on:
  push:
    branches: [ master ]

jobs:
  update-hash:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run mint_block.py to generate metadata_block.json
      run: python blockchain/mint_block.py

    - name: Commit and push updated metadata_block.json
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add docs/metadata_block.json
        git commit -m "Update metadata block"
        git push
